let failwith (message: string) => failwith message;